Loading组件实现
jdf2e/nutui-react pull request #1204
Opened 2023-07-09 15:43 UTC by mike8625

### 🤔 这个变动的性质是？

- [☑️ ] 新特性提交

### 🔗 相关 Issue

https://github.com/jdf2e/nutui-rfcs/blob/main/react/Loading.md

### 💡 需求背景和解决方案

实现了nutui2.0的loading组件的h5版本, 引入Loading组件后, 使用`<Loading/>`标签即可显示.

目前由于我是在windows10中开发,试了很多方法都无法启动taro版本的小程序,询问了几个大佬,他们都是在mac下开发. 所以taro的代码目前都是盲写的,已经把config.json中的taro设置为了false.
本来想等windows中可以测试完成后再提pr, 但是询问了佟小牙大佬后,她说先提交一下,taro的功能后面再完善.

### ☑️ 请求合并前的自查清单

⚠️ 请自检并全部**勾选全部选项**。⚠️

- [☑️ ] 文档已补充或无须补充
- [☑️ ] 代码演示已提供或无须提供
- [☑️ ] TypeScript 定义已补充或无须补充
- [☑️ ] fork仓库代码是否为最新避免文件冲突
- [☑️ ] Files changed 没有 package.json lock 等无关文件

2023-07-26 03:30 UTC, xiaoyatong commented on src/packages/loading/loading.tsx
> +  // loading的大小 下面会把size转成width和height
以下属性可使用 css 变量来处理。

2023-07-26 03:30 UTC, xiaoyatong commented on src/packages/loading/loading.tsx
> +  color: '#9EA9AF',
默认值 需要考虑 主题定制。

2023-07-26 03:30 UTC, xiaoyatong commented on src/packages/loading/loading.tsx
> +        {icon || <CurLoadingIcon color={color} width={size} height={size} />}
我是这样理解的：
要么用户直接使用 自定义icon，要么按照规范来实现。所以后边这个可以不处理color 等属性，按默认即可。

2023-07-26 03:30 UTC, xiaoyatong commented on src/packages/loading/loading.tsx
> +          style={{
可在主题中实现。

2023-07-28 08:19 UTC, mike8625 commented
大佬,已经按您的要求修改了部分属性,横纵向布局改成了通用的direction属性,把关于颜色和字体的属性也去掉了,改成可以配置主题的方式. 另外这次更新后,taro我也可以在windows运行起来了,小程序也跑通了,所以在config.ts里面把taro改成了true. 请核验.

2023-07-31 02:10 UTC, oasis-cloud requested changes

2023-07-31 02:10 UTC, oasis-cloud commented on src/config.json
> +          "version": "1.0.0",
版本号需要修改为 2.0.0

2023-07-31 02:10 UTC, oasis-cloud commented on src/packages/loading/index.ts
> +
需要导出 DirectionType 和 LoadingType 类型，taro 的实现也需要处理

2023-07-31 02:10 UTC, oasis-cloud commented on src/packages/loading/loading.tsx
> +  icon?: JSX.Element
icon 类型改为 ReactNode

2023-07-31 07:33 UTC, mike8625 commented on src/config.json
> +          "version": "1.0.0",
已修正版本号改为2.0

2023-07-31 07:33 UTC, mike8625 commented on src/packages/loading/index.ts
> +
已将两个文件添加了 DirectionType 和 LoadingType 类型

2023-07-31 07:33 UTC, mike8625 commented on src/packages/loading/loading.tsx
> +  icon?: JSX.Element
已修改为ReactNode

2023-07-31 07:41 UTC, mike8625 commented
大佬们,您指出的问题,已全部修正

2023-08-03 03:48 UTC, merged