avatar头像组件更新和测试用例编写
jdf2e/nutui-react pull request #121
Opened 2022-05-06 12:13 UTC by junjun666

本次更新内容如下：
1）更新Avatar头像组件，同步官方vue3的最新3.1.20版本
2）调整Avatar头像组件文档为官方最新文档
3）新增AvatarGroup子组件
4）编写Avatar头像组件测试用例
5）编写AvatarGroup子组件测试用例

2022-05-10 07:57 UTC, oasis-cloud commented on src/packages/avatar/demo.scss
> +.nut-cell {
目前 demo 不支持 css module，这里建议在 demo 中控制 nut-cell 的样式，例如： .demo-avatar {
   .nut-cell {
       xxx:xxx
    }
}

2022-05-10 07:57 UTC, oasis-cloud commented on src/packages/avatar/doc.md
这里需要加上 :::

2022-05-17 03:18 UTC, oasis-cloud requested changes

2022-05-17 03:18 UTC, oasis-cloud commented on src/packages/circleprogress/circleprogress.tsx
> +  strokeWidth?: string | number
属性名称变了，线上用户升级会有问题，需要整理下本次 pr 哪些组件删除了属性

2022-05-17 03:18 UTC, oasis-cloud commented on src/packages/avatar/avatar.tsx
> +  url: string
属性名称变更

2022-05-17 03:18 UTC, oasis-cloud commented on src/packages/skeleton/skeleton.tsx
> +  height: string
属性用法发生改变

2022-05-17 04:59 UTC, oasis-cloud requested changes

2022-05-17 04:59 UTC, oasis-cloud commented on src/packages/avatargroup/avatargroup.tsx
> +  shape: '',
在 demo.tsx 中设置 shape 未生效

2022-05-17 04:59 UTC, oasis-cloud commented on src/packages/avatar/avatar.tsx
> +  alt: string
url 设置为 https://imgs12.360buyimg.com/imagetools/jfs/t1/196430/38/8105/14329/60c806a4Ed506298a/e6de9fb7b8490f38.png，alt 属性未展示

2022-05-17 05:12 UTC, oasis-cloud requested changes

2022-05-17 05:12 UTC, oasis-cloud commented on src/packages/skeleton/demo.tsx
> +        <Skeleton width="250px" height="15px" animated />
width="100" 时，skeleton未展示，在文档中写明 width 和 height需要的单位

2022-05-17 05:12 UTC, oasis-cloud commented on src/packages/skeleton/demo.tsx
> +        <Skeleton width="250px" height="15px" />
Skeleton loading width="250px" height="15px"  未展示

2022-05-17 05:25 UTC, oasis-cloud requested changes

2022-05-17 05:25 UTC, oasis-cloud commented on src/packages/steps/doc.md
>  | size          | 图标尺寸大小       | String | '' |
可以给出 size 的例子，例如 large small 或 100px

2022-05-17 05:25 UTC, oasis-cloud commented on src/packages/steps/doc.md
>  | icon          | 图标       | String | '' |
icon 的取值可以写明 来自 icon 组件中的名字

2022-05-17 05:25 UTC, oasis-cloud commented on src/packages/steps/demo.tsx
>                1
这里的 1 的实际作用是什么，没有用的话可以删掉

2022-05-17 08:14 UTC, junjun666 commented on src/packages/avatargroup/avatargroup.tsx
> +  shape: '',
已修复~

2022-05-17 08:17 UTC, junjun666 commented on src/packages/avatar/avatar.tsx
> +  alt: string
已修复~

2022-05-17 08:40 UTC, junjun666 commented on src/packages/skeleton/demo.tsx
> +        <Skeleton width="250px" height="15px" animated />
文档已更新~

2022-05-17 08:40 UTC, junjun666 commented on src/packages/skeleton/demo.tsx
> +        <Skeleton width="250px" height="15px" />
文档已补充更新~

2022-05-17 09:03 UTC, junjun666 commented on src/packages/steps/demo.tsx
>                1
先与官方对齐~

2022-05-17 09:07 UTC, junjun666 commented on src/packages/steps/doc.md
>  | size          | 图标尺寸大小       | String | '' |
已完善文档~

2022-05-17 09:08 UTC, junjun666 commented on src/packages/steps/doc.md
>  | icon          | 图标       | String | '' |
已完善文档~

2022-05-19 07:24 UTC, merged