fix(Address): 修复Address组件通过点击CloseIcon和Overlay关闭后，无法再次打开的问题
jdf2e/nutui-react pull request #1233
Opened 2023-07-16 19:03 UTC by TralafalgarV

### 🤔 这个变动的性质是？

- [ ] 新特性提交
- [ x] 日常 bug 修复
- [ ] 站点、文档改进
- [ ] 演示代码改进
- [ ] 组件样式/交互改进
- [ ] TypeScript 定义更新
- [ ] 包体积优化
- [ ] 性能优化
- [ ] 功能增强
- [ ] 国际化改进
- [ ] 重构
- [ ] 代码风格优化
- [ ] 测试用例
- [ ] 分支合并
- [ ] 其他改动（是关于什么的改动？）

### 🔗 相关 Issue

### 💡 需求背景和解决方案
目前 Address 通过props传入的 `visible` 属性来控制组件的显示和隐藏。当组件通过点击 CloseIcon 和 Overlay 关闭后，它没有调用传入的 `onClose` 方法来通知父组件变更 `visible` 状态。从而导致`Address`组件无法再次展示。

PS：项目提供的[demo](https://github.com/jdf2e/nutui-react/blob/837422027b6fd35adb8ae62ab10f9b4fb3a5c523/src/packages/address/demo.taro.tsx#L353C9-L353C20)中，`showAddress`方法通过取反来改变`visible`状态，恰巧规避了这个问题，但是又没有完全规避。需要点击两次，才能正常展示Address。

### ☑️ 请求合并前的自查清单

⚠️ 请自检并全部**勾选全部选项**。⚠️

- [ x] 文档已补充或无须补充
- [ x] 代码演示已提供或无须提供
- [ x] TypeScript 定义已补充或无须补充
- [x ] fork仓库代码是否为最新避免文件冲突
- [x ] Files changed 没有 package.json lock 等无关文件

2023-07-17 02:45 UTC, oasis-cloud requested changes
visible 可用于受控，可考虑增加 defaultVisible 用于非受控，这样就可以不加 onClose 来处理父组件中的状态。

在这个 PR 中，md 文档并没有进行对应的修改

2023-07-18 02:50 UTC, TralafalgarV commented
> visible 可用于受控，可考虑增加 defaultVisible 用于非受控，这样就可以不加 onClose 来处理父组件中的状态。
> 
> 在这个 PR 中，md 文档并没有进行对应的修改

有个疑问：如果 `Address` 组件添加 `defaultVisible` 属性用于非受控，是否需要通过 `forwardRef `对外暴露 `onOpen` 和 `onClose` 方法。方便用户进行**显示**和**隐藏**的状态切换？亦或用户直接在父组件通过一个状态来控制Address组件的挂载与卸载即可？

2023-07-18 05:28 UTC, oasis-cloud commented
> > visible 可用于受控，可考虑增加 defaultVisible 用于非受控，这样就可以不加 onClose 来处理父组件中的状态。
> > 在这个 PR 中，md 文档并没有进行对应的修改
> 
> 有个疑问：如果 `Address` 组件添加 `defaultVisible` 属性用于非受控，是否需要通过 `forwardRef `对外暴露 `onOpen` 和 `onClose` 方法。方便用户进行**显示**和**隐藏**的状态切换？亦或用户直接在父组件通过一个状态来控制Address组件的挂载与卸载即可？

可以对 ref 增加 open 和 close 的方法，用于显示和隐藏的触发

2023-07-19 03:51 UTC, TralafalgarV commented
> > > visible 可用于受控，可考虑增加 defaultVisible 用于非受控，这样就可以不加 onClose 来处理父组件中的状态。
> > > 在这个 PR 中，md 文档并没有进行对应的修改
> > 
> > 
> > 有个疑问：如果 `Address` 组件添加 `defaultVisible` 属性用于非受控，是否需要通过 `forwardRef `对外暴露 `onOpen` 和 `onClose` 方法。方便用户进行**显示**和**隐藏**的状态切换？亦或用户直接在父组件通过一个状态来控制Address组件的挂载与卸载即可？
> 
> 可以对 ref 增加 open 和 close 的方法，用于显示和隐藏的触发

已添加相关功能，并更新文档和demo

2023-07-20 06:21 UTC, oasis-cloud approved these changes

2023-07-20 06:21 UTC, merged