fix(Uploader): 设置fit 属性无效
jdf2e/nutui-react pull request #1559
Opened 2023-10-23 09:56 UTC by beginnerZhang

### 🤔 这个变动的性质是？

- [ ] 新特性提交
- [x] 日常 bug 修复
- [ ] 站点、文档改进
- [ ] 演示代码改进
- [ ] 组件样式/交互改进
- [ ] TypeScript 定义更新
- [ ] 包体积优化
- [ ] 性能优化
- [ ] 功能增强
- [ ] 国际化改进
- [ ] 重构
- [ ] 代码风格优化
- [ ] 测试用例
- [ ] 分支合并
- [ ] 其他改动（是关于什么的改动？）

### 🔗 相关 Issue

### 💡 需求背景和解决方案

### ☑️ 请求合并前的自查清单

⚠️ 请自检并全部**勾选全部选项**。⚠️

- [ ] 文档已补充或无须补充
- [ ] 代码演示已提供或无须提供
- [ ] TypeScript 定义已补充或无须补充
- [ ] fork仓库代码是否为最新避免文件冲突
- [ ] Files changed 没有 package.json lock 等无关文件

2023-10-24 03:18 UTC, oasis-cloud requested changes

2023-10-24 03:18 UTC, oasis-cloud commented on src/packages/uploader/preview.taro.tsx
> +                          style={{ objectFit: fit }}
taro 实现上把 style 去掉，采用 mode 属性实现，taro 版本文档中的描述类型改一下，可参考 taro 官方的 image 组件的 mode 类型

2023-10-25 02:10 UTC, oasis-cloud approved these changes

2023-10-25 02:10 UTC, closed without merging

2024-11-18 02:19 UTC, Phyzait commented
这个问题后续没有继续跟进吗？最新代码依然不能设置fit @oasis-cloud