feat: 类似微信头像裁剪组件
jdf2e/nutui-react pull request #1564
Opened 2023-10-25 09:07 UTC by yi-boide

## 新增组件avatarcropper，仿微信头像裁剪组件

### 🤔 这个变动的性质是？

- [x] 新特性提交
- [ ] 日常 bug 修复
- [x] 站点、文档改进
- [x] 演示代码改进
- [ ] 组件样式/交互改进
- [ ] TypeScript 定义更新
- [ ] 包体积优化
- [ ] 性能优化
- [ ] 功能增强
- [ ] 国际化改进
- [ ] 重构
- [ ] 代码风格优化
- [ ] 测试用例
- [ ] 分支合并
- [ ] 其他改动（是关于什么的改动？）

### 🔗 相关 Issue

### 💡 需求背景和解决方案

### ☑️ 请求合并前的自查清单

⚠️ 请自检并全部**勾选全部选项**。⚠️

- [x] 文档已补充或无须补充
- [x] 代码演示已提供或无须提供
- [x] TypeScript 定义已补充或无须补充
- [x] fork仓库代码是否为最新避免文件冲突
- [x] Files changed 没有 package.json lock 等无关文件

2023-10-26 01:46 UTC, oasis-cloud commented on src/packages/avatarcropper/doc.md
> +### 介绍
这里应该是二级标题

2023-10-26 01:46 UTC, oasis-cloud commented on src/packages/avatarcropper/doc.md
> +### 安装
这里应该是二级标题

2023-10-26 01:46 UTC, oasis-cloud commented on src/packages/avatarcropper/doc.md
> +### 基础用法
这里应该是二级标题

2023-10-26 02:22 UTC, oasis-cloud requested changes

2023-10-26 02:22 UTC, oasis-cloud commented on src/packages/avatarcropper/doc.md
> +## API
改为组件名称，按照 React 中使用的名称书写

2023-10-26 02:22 UTC, oasis-cloud commented on src/packages/avatarcropper/doc.md
> +### AvatarCropper Props
只保留 Props，文档格式可以参考其他组件

2023-10-26 02:22 UTC, oasis-cloud commented on src/packages/avatarcropper/doc.md
> +| maxZoom         | 最大缩放倍数                                | number | 3      |
表格的书写，可以参考其他组件，尤其是类型和默认值需要加上`\`\``

2023-10-26 02:22 UTC, oasis-cloud commented on src/packages/avatarcropper/doc.md
> +| onConfirm       | 裁剪后点击确认触发                    | Function(url: string) |  - |
Function 类型可改为 (url: string) => void

2023-10-26 02:22 UTC, oasis-cloud commented on src/packages/avatarcropper/doc.md
> +### AvatarCropper Ref
直接改为 Ref

2023-10-26 02:22 UTC, oasis-cloud commented on src/packages/avatarcropper/avatarcropper.tsx
> +              <Refresh2 color="#fff" />
目前旋转和还原功能的 Icon 表示意义不太容易区分，建议此按钮改为文案 '还原'

2023-10-27 02:19 UTC, xiaoyatong commented
按钮可使用系统默认按钮：
![image](https://github.com/jdf2e/nutui-react/assets/84436086/6a2e7d1d-b076-484a-a5c4-78517cf38567)
选择图片后，样式错乱：
![image](https://github.com/jdf2e/nutui-react/assets/84436086/3c380634-da20-422e-bc58-ecc5ed5b40a7)
截取后，图片过糊：
![image](https://github.com/jdf2e/nutui-react/assets/84436086/f1f723ac-dc51-4e87-8a80-238477c66f61)
自定义，如何自定义裁剪区：
![image](https://github.com/jdf2e/nutui-react/assets/84436086/28a74955-f4dd-44ea-b6f4-b22f683a6865)

2023-10-27 02:21 UTC, yi-boide commented
> 按钮可使用系统默认按钮： ![image](https://user-images.githubusercontent.com/84436086/278518516-6a2e7d1d-b076-484a-a5c4-78517cf38567.png) 选择图片后，样式错乱： ![image](https://user-images.githubusercontent.com/84436086/278518465-3c380634-da20-422e-bc58-ecc5ed5b40a7.png) 截取后，图片过糊： ![image](https://user-images.githubusercontent.com/84436086/278518733-f1f723ac-dc51-4e87-8a80-238477c66f61.png) 自定义，如何自定义裁剪区： ![image](https://user-images.githubusercontent.com/84436086/278518820-28a74955-f4dd-44ea-b6f4-b22f683a6865.png)

你是运行的那个环境的？

2023-10-27 02:24 UTC, yi-boide commented
> 按钮可使用系统默认按钮： ![image](https://user-images.githubusercontent.com/84436086/278518516-6a2e7d1d-b076-484a-a5c4-78517cf38567.png) 选择图片后，样式错乱： ![image](https://user-images.githubusercontent.com/84436086/278518465-3c380634-da20-422e-bc58-ecc5ed5b40a7.png) 截取后，图片过糊： ![image](https://user-images.githubusercontent.com/84436086/278518733-f1f723ac-dc51-4e87-8a80-238477c66f61.png) 自定义，如何自定义裁剪区： ![image](https://user-images.githubusercontent.com/84436086/278518820-28a74955-f4dd-44ea-b6f4-b22f683a6865.png)

你是怎么运行的？我这边运行是正常的
<img width="394" alt="image" src="https://github.com/jdf2e/nutui-react/assets/63292605/42a5567c-bffa-471e-b645-b08b82add4e5">

2023-10-27 03:05 UTC, xiaoyatong commented on src/packages/avatarcropper/avatarcropper.tsx
> +    'nut-cropper-popup__toolbar',
建议变量名和组件保持一致性

2023-10-27 03:06 UTC, xiaoyatong commented on src/packages/avatarcropper/avatarcropper.tsx
> +  maxZoom: 3,
这个可以默认是1~

2023-10-27 03:08 UTC, yi-boide commented on src/packages/avatarcropper/avatarcropper.tsx
> +  maxZoom: 3,
这个是最大放大倍数，1的话相当于不能放大了

2023-10-31 11:22 UTC, xiaoyatong commented
效果不一致：
小程序：
<img width="115" alt="image" src="https://github.com/jdf2e/nutui-react/assets/84436086/32a8e20e-6d92-43d3-af7f-b401860451d2">
H5：
<img width="112" alt="image" src="https://github.com/jdf2e/nutui-react/assets/84436086/16a634b1-ddfe-4dbd-a6ab-b07899ae0c5a">

2023-10-31 11:52 UTC, yi-boide commented
这个问题是Avatar组件传入src的图片地址，在小程序端有bug，高度会直接变成100px，导致图片显示效果被拉伸



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年10月31日(周二) 晚上7:23
收件人: ***@***.***&gt;;
抄送: "Marvin ***@***.******@***.***&gt;;
主题: Re: [jdf2e/nutui-react] feat: 类似微信头像裁剪组件 (PR #1564)




 
效果不一致：
 小程序：
 
 H5：
 
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

2023-11-01 03:13 UTC, xiaoyatong commented on src/packages/avatarcropper/avatarcropper.scss
> +  &__input {
样式部分不再使用BEM规范，直接使用 - 替换掉 __ 即可~

2023-11-01 03:13 UTC, xiaoyatong commented on src/packages/avatarcropper/doc.md
> +| toolbar         | 自定义裁剪区域工具栏                       |  `ReactNode`   |  `-` |
toolbar 和 toolbarPosition 可以写在一起，标记一下，当他们生效的时候，editText 这些是不生效的。

2023-11-01 03:13 UTC, xiaoyatong commented on src/packages/avatarcropper/avatarcropper.tsx
> +              <Button type="danger">{cancelText}</Button>
Button 这些子项，是不是可以放在一个list里，遍历渲染？

2023-11-01 03:13 UTC, xiaoyatong commented on src/packages/avatarcropper/avatarcropper.tsx
> +          toolbar
我个人还是认为：toolbar 可以作为一个actions 数组，然后可以自定义。
而 editText cancelText 等，都可以为 node 节点。
我们可以小窗沟通一下。

2023-11-01 03:13 UTC, xiaoyatong commented on src/packages/avatarcropper/avatarcropper.scss
> +      width: 365px;
可修改，可暴露变量。

2023-11-01 03:13 UTC, xiaoyatong commented on src/packages/avatarcropper/avatarcropper.scss
> +      z-index: 1;
这个为什么还要写~

2023-11-08 12:20 UTC, merged