feat: theme updated to v12
jdf2e/nutui-react pull request #1573
Opened 2023-10-31 02:18 UTC by xiaoyatong

### 🤔 这个变动的性质是？

- [x] 新特性提交
- [x] 日常 bug 修复
- [ ] 站点、文档改进
- [x] 演示代码改进
- [x] 组件样式/交互改进
- [ ] TypeScript 定义更新
- [ ] 包体积优化
- [ ] 性能优化
- [ ] 功能增强
- [ ] 国际化改进
- [ ] 重构
- [x] 代码风格优化
- [ ] 测试用例
- [ ] 分支合并
- [ ] 其他改动（是关于什么的改动？）

### 🔗 相关 Issue

### 💡 需求背景和解决方案

### ☑️ 请求合并前的自查清单

⚠️ 请自检并全部**勾选全部选项**。⚠️

- [ ] 文档已补充或无须补充
- [ ] 代码演示已提供或无须提供
- [ ] TypeScript 定义已补充或无须补充
- [ ] fork仓库代码是否为最新避免文件冲突
- [ ] Files changed 没有 package.json lock 等无关文件

2023-11-08 03:34 UTC, oasis-cloud requested changes

2023-11-08 03:34 UTC, oasis-cloud commented on src/styles/theme-dark.scss
> +  // --nutui-black-4: rgba(0, 0, 0, 0.1);
black 和 white 是待扩充状态吗？

2023-11-08 03:34 UTC, oasis-cloud commented on src/packages/button/button.tsx
> -  | 'info'
什么原因删除了 info 类型

2023-11-08 03:34 UTC, oasis-cloud commented on src/packages/button/doc.md
>        <Button fill="solid">Solid</Button>
文档和 Demo 不一致，缺少 Dashed

2023-11-08 03:34 UTC, oasis-cloud commented on src/packages/button/doc.md
> +### 图标按钮
文档和 demo 不一致

2023-11-08 03:34 UTC, oasis-cloud commented on src/packages/button/doc.md
> +      <Button
文档和 Demo 不一致

2023-11-08 03:34 UTC, oasis-cloud commented on src/packages/button/doc.md
>        <Button shape="square" type="primary">方形按钮</Button>
文档和 Demo 不一致

2023-11-08 03:34 UTC, oasis-cloud commented on src/packages/button/doc.md
>  ### 按钮尺寸
文档和 Demo 不一致

2023-11-08 03:34 UTC, oasis-cloud commented on src/packages/button/demo.taro.tsx
> +      '60a53514': '操作按鈕',
Taro H5 下按钮存在黑色边框，同时需要查看文档和 Demo 是否一致

2023-11-08 03:34 UTC, oasis-cloud commented on src/packages/cell/demo.tsx
> +              <User />
垂直居中的例子中，"描述文字"未垂直居中，Taro H5 下是垂直剧中的。

2023-11-08 03:34 UTC, oasis-cloud commented on src/packages/elevator/elevator.scss
> +    top: 0;
position 设置 relative后，top如果是0，应该不需要特别设置

2023-11-08 03:34 UTC, oasis-cloud commented on src/packages/navbar/demo.taro.tsx
> +              <Share size={20} />
Icon 的大小和 H5 的 demo 不一致

2023-11-08 03:34 UTC, oasis-cloud commented on src/packages/tabs/tabs.scss
> +        position: absolute;
在 H5 的 demo 中 微笑曲线紧贴文字，看上去是样式错了

2023-11-08 03:34 UTC, oasis-cloud commented on src/packages/address/demo.taro.tsx
> +    defaultIcon: <Heart />,
Taro H5 中自定义图标颜色不对，应该是红色的，现在是黑色的

2023-11-08 03:34 UTC, oasis-cloud commented on src/packages/checkbox/demo.taro.tsx
> +            checked
taro h5 下 checked 未生效

2023-11-08 03:34 UTC, oasis-cloud commented on src/packages/form/demo.taro.tsx
> +import { ArrowRight } from '@nutui/icons-react-taro'
Taro H5 下基础用法没有分割线，H5 下有分割线

2023-11-08 03:34 UTC, oasis-cloud commented on src/packages/menu/menu.scss
> +  &-icon {
没有和菜单标题的问题水平对齐

2023-11-08 03:34 UTC, oasis-cloud commented on src/packages/menuitem/menuitem.scss
> +    &.active {
菜单选项前面的对号图标大小在 Taro和 H5 下不一致

2023-11-08 03:34 UTC, oasis-cloud commented on src/packages/searchbar/demo.tsx
> +            <>
自定义设置 Demo 中的 ArrowDown 在 taro 和 h5 下大小是否需要统一

2023-11-08 03:34 UTC, oasis-cloud commented on src/packages/switch/switch.taro.tsx
> +              <div className={`${classPrefix}-label open`}>{activeText}</div>
在 taro 和 h5 中文字的位置不一致

2023-11-08 06:05 UTC, oasis-cloud requested changes

2023-11-08 06:05 UTC, oasis-cloud commented on src/packages/noticebar/demo.tsx
> +        <NoticeBar closeable rightIcon={<Failure />} onClick={hello}>
Taro H5 下会出现 Cannot read properties of null (reading 'style') 的错误提示

2023-11-08 06:05 UTC, oasis-cloud commented on src/packages/notify/notify.scss
> +  &--popup-top,
Taro H5 下自定义样式和 H5 下的自定义样式的 demo 表现不一致

2023-11-08 06:05 UTC, oasis-cloud commented on src/packages/popover/popover.taro.tsx
> +  action?: { icon?: React.ReactNode; onClick?: (e: any) => void }
Taro H5 下报错 TypeError: Cannot read properties of undefined (reading 'MODE')

2023-11-08 06:05 UTC, oasis-cloud commented on src/packages/skeleton/skeleton.scss
> +      var(--nutui-white-1),
Taro H5 下 skeleton 组件的"显示子组件" Demo 的图片不能展示

2023-11-08 06:05 UTC, oasis-cloud commented on src/packages/circleprogress/circleprogress.taro.tsx
> +  color: '',
Taro H5 下 circleprogress 组件的 demo 展示错误

2023-11-08 06:05 UTC, oasis-cloud commented on src/packages/swiper/demo.tsx
> +import { ArrowLeft, ArrowRight } from '@nutui/icons-react'
Taro H5 下的 swiper 指示器显示不出来，需要合并 next 的最新代码

2023-11-08 06:05 UTC, oasis-cloud commented on src/packages/tag/demo.taro.tsx
> +                closeIcon={<Failure width={8} height={8} />}
关闭按钮太大

2023-11-08 06:05 UTC, oasis-cloud commented on src/packages/tour/demo.taro.tsx
>              '--nutui-popover-content-background-color': 'rgb(75, 76, 77)',
在 Taro H5 中，三角箭头的颜色和背景颜色差异明显

2023-11-29 07:43 UTC, xiaoyatong commented on src/packages/button/button.tsx
> -  | 'info'
已恢复。

2023-11-29 07:43 UTC, xiaoyatong commented on src/packages/button/doc.md
>        <Button fill="solid">Solid</Button>
已增加

2023-11-29 07:44 UTC, xiaoyatong commented on src/packages/button/doc.md
> +### 图标按钮
fixed

2023-11-29 07:44 UTC, xiaoyatong commented on src/packages/button/doc.md
> +      <Button
fixed

2023-11-29 11:11 UTC, xiaoyatong commented on src/styles/theme-dark.scss
> +  // --nutui-black-4: rgba(0, 0, 0, 0.1);
对，现在仅对用的上的做了处理。

2023-11-29 11:11 UTC, xiaoyatong commented on src/packages/button/doc.md
>        <Button shape="square" type="primary">方形按钮</Button>
fixed

2023-11-29 11:11 UTC, xiaoyatong commented on src/packages/button/demo.taro.tsx
> +      '60a53514': '操作按鈕',
fixed

2023-11-29 11:12 UTC, xiaoyatong commented on src/packages/button/doc.md
>  ### 按钮尺寸
fixed

2023-11-29 11:16 UTC, xiaoyatong commented on src/packages/swiper/demo.tsx
> +import { ArrowLeft, ArrowRight } from '@nutui/icons-react'
fixed

2023-12-06 09:26 UTC, oasis-cloud commented
<img width="363" alt="image" src="https://github.com/jdf2e/nutui-react/assets/12181600/20bb24af-504b-4b44-8769-7af701f9334d">
button 出现黑色边框

2023-12-06 09:55 UTC, oasis-cloud commented on src/packages/drag/demo.taro.tsx
> +import Button from '@/packages/button/index.taro'
这样引入不对

2023-12-06 10:08 UTC, oasis-cloud commented
<img width="463" alt="image" src="https://github.com/jdf2e/nutui-react/assets/12181600/5d5b9799-737a-44da-b843-128b9376d106">
popup 顶部弹出应该有圆角，底部弹出应该没有圆角。

2023-12-06 10:15 UTC, oasis-cloud commented on src/packages/trendarrow/trendarrow.tsx
> +  color: '',
taro 的为什么没有去掉默认值？

2023-12-06 10:16 UTC, oasis-cloud commented on src/packages/trendarrow/trendarrow.tsx
> +  color: '',
taro的为什么没有去掉默认值

2023-12-06 10:17 UTC, oasis-cloud commented on src/packages/trendarrow/trendarrow.tsx
> +  color: '',
taro 的为什么没有去掉默认值？

2023-12-06 10:26 UTC, oasis-cloud requested changes

2023-12-06 10:26 UTC, oasis-cloud commented on scripts/test-generate-demo-tsx.js
> +const fse = require('fs-extra')
可以在文件开头写下整体的功能描述

2023-12-06 10:26 UTC, oasis-cloud commented on scripts/test-generate-demo-tsx.js
> +const mypath = `/Users/tongen/Documents/开源/UI-Demos/my-nutui-22`
把你路径换成可传入的变量吗？

2023-12-06 10:27 UTC, oasis-cloud commented
lint test build 的 ci 都没通过

2023-12-06 10:30 UTC, oasis-cloud commented
range/demo.taro.tsx 中的 import '@/packages/range/demo.scss' 需要删除

2023-12-06 10:33 UTC, oasis-cloud commented
<img width="443" alt="image" src="https://github.com/jdf2e/nutui-react/assets/12181600/f12db1e1-bc52-4a94-9f45-68aaa62905cd">
taro h5 按钮展示不出来

2023-12-06 10:36 UTC, oasis-cloud commented
<img width="422" alt="image" src="https://github.com/jdf2e/nutui-react/assets/12181600/cadf9943-a0e5-40b7-9ceb-24d484172141">
背景色应该是白色的？

2023-12-06 10:39 UTC, oasis-cloud commented
<img width="406" alt="image" src="https://github.com/jdf2e/nutui-react/assets/12181600/9ddd55c4-fbaa-4738-aed3-d448a35daed0">

2023-12-06 10:41 UTC, oasis-cloud commented
<img width="417" alt="image" src="https://github.com/jdf2e/nutui-react/assets/12181600/4f896706-544e-4aa0-a35a-46bc82cdaf59">
没有头部导航

2023-12-06 10:42 UTC, oasis-cloud commented
<img width="412" alt="image" src="https://github.com/jdf2e/nutui-react/assets/12181600/e0ce5eb3-67a0-40b3-8194-8042e84c5989">

2023-12-06 11:57 UTC, xiaoyatong commented on src/packages/drag/demo.taro.tsx
> +import Button from '@/packages/button/index.taro'
fixed

2023-12-06 11:57 UTC, xiaoyatong commented on src/packages/trendarrow/trendarrow.tsx
> +  color: '',
去掉就报错了。与实现部分有关系。

2023-12-06 11:58 UTC, xiaoyatong commented on scripts/test-generate-demo-tsx.js
> +const fse = require('fs-extra')
已删除。

2023-12-06 12:02 UTC, xiaoyatong commented
popup 底部弹出默认圆角；
loading头部导航已加
navbar是使用了新的视觉规范
待办：日历、menu、toast

2023-12-07 09:32 UTC, oasis-cloud commented
npm lock 文件中的源配置不对

2023-12-07 09:33 UTC, oasis-cloud commented
<img width="372" alt="image" src="https://github.com/jdf2e/nutui-react/assets/12181600/e7eecf3c-c4e3-487c-a9cd-862327ab267c">
checkbox 选中禁用的样式可能需要修改

2023-12-07 09:33 UTC, oasis-cloud commented
<img width="424" alt="image" src="https://github.com/jdf2e/nutui-react/assets/12181600/bb316934-034f-4dcf-8dde-5ba87ed3c584">
radio 选中禁用的样式需要再确认一下

2023-12-07 10:11 UTC, oasis-cloud commented
<img width="656" alt="image" src="https://github.com/jdf2e/nutui-react/assets/12181600/11014747-cb62-41be-b063-ca70a6000e0b">
![image](https://github.com/jdf2e/nutui-react/assets/12181600/35ecbc1d-fd27-458e-b820-82b819d5040a)
是不是应该是虚线边框

2023-12-08 02:47 UTC, oasis-cloud commented
> <img alt="image" width="372" src="https://private-user-images.githubusercontent.com/12181600/288707658-e7eecf3c-c4e3-487c-a9cd-862327ab267c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE5NDYzMzMsIm5iZiI6MTcwMTk0NjAzMywicGF0aCI6Ii8xMjE4MTYwMC8yODg3MDc2NTgtZTdlZWNmM2MtYzRlMy00ODdjLWE5Y2QtODYyMzI3YWIyNjdjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA3VDEwNDcxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI5MjJjMTg2OWE3ZmYzYWZjOWYwNTU5ZWNkMzZiNjljZDg3NzEzOTliM2UyYTA3YTMxMmZhOGMxOWE3ZmNkYmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nmlMoYuI8K47J3KXXOdkxnUci9JAXEbk-vEynq7Pczc"> checkbox 选中禁用的样式可能需要修改，对钩的位置不对

对钩位置已修改

2023-12-08 05:19 UTC, merged