refactor: elevator css and variables
jdf2e/nutui-react pull request #1668
Opened 2023-11-21 11:19 UTC by xiaoyatong

### 🤔 这个变动的性质是？

- [ ] 新特性提交
- [ ] 日常 bug 修复
- [ ] 站点、文档改进
- [ ] 演示代码改进
- [ ] 组件样式/交互改进
- [ ] TypeScript 定义更新
- [ ] 包体积优化
- [ ] 性能优化
- [ ] 功能增强
- [ ] 国际化改进
- [ ] 重构
- [ ] 代码风格优化
- [ ] 测试用例
- [ ] 分支合并
- [ ] 其他改动（是关于什么的改动？）

### 🔗 相关 Issue

### 💡 需求背景和解决方案

### ☑️ 请求合并前的自查清单

⚠️ 请自检并全部**勾选全部选项**。⚠️

- [ ] 文档已补充或无须补充
- [ ] 代码演示已提供或无须提供
- [ ] TypeScript 定义已补充或无须补充
- [ ] fork仓库代码是否为最新避免文件冲突
- [ ] Files changed 没有 package.json lock 等无关文件

2023-11-21 13:59 UTC, oasis-cloud requested changes

2023-11-21 13:59 UTC, oasis-cloud commented on src/packages/elevator/doc.zh-TW.md
> +import { Elevator } from '@nutui/nutui-react-taro'
引入的包不对

2023-11-21 13:59 UTC, oasis-cloud commented on src/packages/elevator/doc.zh-TW.md
> +import { Elevator } from '@nutui/nutui-react-taro'
引入的包不对

2023-11-21 13:59 UTC, oasis-cloud commented on src/packages/elevator/doc.zh-TW.md
> +import { Elevator } from '@nutui/nutui-react-taro'
引入的包不对

2023-11-21 13:59 UTC, oasis-cloud commented on src/packages/elevator/doc.zh-TW.md
> +import { Jd } from '@nutui/icons-react-taro'
引入的包不对

2023-11-21 13:59 UTC, oasis-cloud commented on src/packages/elevator/doc.zh-TW.md
> +import { Elevator } from '@nutui/nutui-react-taro'
引入的包不对

2023-11-21 13:59 UTC, oasis-cloud commented on src/packages/elevator/doc.zh-TW.md
> +import { Elevator } from '@nutui/nutui-react-taro'
引入的包不对

2023-11-22 01:06 UTC, xiaoyatong commented
fixed

2023-11-22 01:44 UTC, oasis-cloud approved these changes

2023-11-22 01:44 UTC, merged