新增video视频组件
jdf2e/nutui-react pull request #174
Opened 2022-07-25 10:07 UTC by junjun666

1.video视频组件开发
2.单元测试开发检测
3.demo多语言支持
4.文档多语言支持

2022-07-26 03:28 UTC, oasis-cloud commented on src/packages/video/video.tsx
> +  useEffect(() => {
空的 useEffect

2022-07-26 03:28 UTC, oasis-cloud commented on src/packages/video/video.tsx
> +          JSON.stringify(options.playsinline)
JSON的操作容易抛出错误

2022-07-26 03:28 UTC, oasis-cloud commented on src/packages/video/video.tsx
> +    <div className="nut-video">
支持 className和 style 吗？

2022-07-26 03:28 UTC, oasis-cloud commented on src/packages/video/demo.scss
> +.demo {
可采用 demo-video 来命名，demo的打包没有采用module css

2022-07-27 07:36 UTC, junjun666 commented on src/packages/video/video.tsx
> +  useEffect(() => {
已修复~

2022-07-27 07:46 UTC, junjun666 commented on src/packages/video/video.tsx
> +    <div className="nut-video">
已添加支持~

2022-07-27 08:21 UTC, junjun666 commented on src/packages/video/demo.scss
> +.demo {
已增加demo-video命名

2022-07-29 07:22 UTC, junjun666 commented on src/packages/video/video.tsx
> +          JSON.stringify(options.playsinline)
已修改String判断

2022-07-29 07:44 UTC, yangjinjun3 requested changes

2022-07-29 07:45 UTC, junjun666 commented on src/packages/video/doc.md
> +| options             | 控制视频播放属性                           | Object  | required |
暂不支持

2022-07-29 07:45 UTC, junjun666 commented on src/packages/video/doc.md
> +| options.disabled    | 禁用操作（如循环播放的背景图，禁止操作）   | Boolean | false    |
文档已修改~

2022-07-29 07:45 UTC, junjun666 commented on src/packages/video/video.tsx
> +    loop: false,
React目前暂不加

2022-08-01 01:38 UTC, oasis-cloud approved these changes

2022-08-01 01:39 UTC, merged