feat(Diolog): 增加关闭按钮
jdf2e/nutui-react pull request #1872
Opened 2024-01-18 02:55 UTC by irisSong

### 🤔 这个变动的性质是？

- [ ] 新特性提交
- [ ] 日常 bug 修复
- [ ] 站点、文档改进
- [ ] 演示代码改进
- [ ] 组件样式/交互改进
- [ ] TypeScript 定义更新
- [ ] 包体积优化
- [ ] 性能优化
- [ ] 功能增强
- [ ] 国际化改进
- [ ] 重构
- [ ] 代码风格优化
- [ ] 测试用例
- [ ] 分支合并
- [ ] 其他改动（是关于什么的改动？）

### 🔗 相关 Issue

### 💡 需求背景和解决方案

### ☑️ 请求合并前的自查清单

⚠️ 请自检并全部**勾选全部选项**。⚠️

- [ ] 文档已补充或无须补充
- [ ] 代码演示已提供或无须提供
- [ ] TypeScript 定义已补充或无须补充
- [ ] fork仓库代码是否为最新避免文件冲突
- [ ] Files changed 没有 package.json lock 等无关文件

2024-01-18 10:03 UTC, oasis-cloud requested changes

2024-01-18 10:03 UTC, oasis-cloud commented on src/packages/dialog/dialog.tsx
> +  closeIconPosition: 'top-right',
增加类型，明确可以使用哪些组合

2024-01-18 10:05 UTC, oasis-cloud requested changes

2024-01-18 10:05 UTC, oasis-cloud commented on src/packages/dialog/dialog.taro.tsx
> +  closeIconPosition: 'top-right',
这里也更新下类型

2024-01-18 10:19 UTC, irisSong commented on src/packages/dialog/dialog.tsx
> +  closeIconPosition: 'top-right',
> 增加类型，明确可以使用哪些组合

已修改

2024-01-18 10:19 UTC, irisSong commented on src/packages/dialog/dialog.taro.tsx
> +  closeIconPosition: 'top-right',
> 这里也更新下类型
已修改

2024-01-19 01:14 UTC, oasis-cloud approved these changes

2024-01-19 01:14 UTC, merged