feat(rate): 新增 touchable 属性支持滑动选择
jdf2e/nutui-react pull request #1880
Opened 2024-01-19 07:25 UTC by eiinu

### 🤔 这个变动的性质是？

- [x] 新特性提交
- [ ] 日常 bug 修复
- [x] 站点、文档改进
- [x] 演示代码改进
- [ ] 组件样式/交互改进
- [ ] TypeScript 定义更新
- [ ] 包体积优化
- [ ] 性能优化
- [x] 功能增强
- [ ] 国际化改进
- [ ] 重构
- [ ] 代码风格优化
- [ ] 测试用例
- [ ] 分支合并
- [ ] 其他改动（是关于什么的改动？）

### 🔗 相关 Issue

### 💡 需求背景和解决方案

### ☑️ 请求合并前的自查清单

⚠️ 请自检并全部**勾选全部选项**。⚠️

- [ ] 文档已补充或无须补充
- [ ] 代码演示已提供或无须提供
- [ ] TypeScript 定义已补充或无须补充
- [ ] fork仓库代码是否为最新避免文件冲突
- [ ] Files changed 没有 package.json lock 等无关文件

2024-01-19 08:31 UTC, xiaoyatong commented
1、可滑动区域是不是稍微放大一下
2、自定义颜色的时候，不生效
3、可以支持绑定事件的触发

2024-01-22 07:08 UTC, oasis-cloud approved these changes

2024-01-24 08:21 UTC, eiinu commented
> 1、可滑动区域是不是稍微放大一下 2、自定义颜色的时候，不生效 3、可以支持绑定事件的触发

已修改

2024-01-24 11:54 UTC, oasis-cloud requested changes

2024-01-24 11:54 UTC, oasis-cloud commented on src/packages/rate/rate.tsx
> +  onTouchEnd: (e: TouchEvent, value: number) => void
可以考虑下只加 touchend 事件，touchStart 和 touchmove 应用场景的频率需要考虑

2024-01-25 01:45 UTC, eiinu commented on src/packages/rate/rate.tsx
> +  onTouchEnd: (e: TouchEvent, value: number) => void
已删除 touchStart & touchMove

2024-01-25 02:35 UTC, merged