fix(configProvider): 文档优化、doc&demo一致化、button demo错字修改
jdf2e/nutui-react pull request #1882
Opened 2024-01-19 08:19 UTC by Alexx12321

### 🤔 这个变动的性质是？

- [ ] 新特性提交
- [ ] 日常 bug 修复
- [x] 站点、文档改进
- [x] 演示代码改进
- [ ] 组件样式/交互改进
- [ ] TypeScript 定义更新
- [ ] 包体积优化
- [ ] 性能优化
- [ ] 功能增强
- [x] 国际化改进
- [ ] 重构
- [ ] 代码风格优化
- [ ] 测试用例
- [ ] 分支合并
- [ ] 其他改动（是关于什么的改动？）

### 🔗 相关 Issue

### 💡 需求背景和解决方案

### ☑️ 请求合并前的自查清单

⚠️ 请自检并全部**勾选全部选项**。⚠️

- [x] 文档已补充或无须补充
- [x] 代码演示已提供或无须提供
- [x] TypeScript 定义已补充或无须补充
- [x] fork仓库代码是否为最新避免文件冲突
- [x] Files changed 没有 package.json lock 等无关文件

2024-01-19 08:30 UTC, oasis-cloud requested changes

2024-01-19 08:30 UTC, oasis-cloud commented on src/packages/configprovider/doc.en-US.md
> +##### Textarea default
为什么这么多层级？

2024-01-19 08:35 UTC, Alexx12321 commented on src/packages/configprovider/doc.en-US.md
> +##### Textarea default
这个组件文档结构和前面不太一样，前面的组件代码演示下面直接就是各部分代码的标题，层级比较低。这个组件代码演示下面已经分了一个层级。而这部分代码演示感觉应该放到【通过 ConfigProvider 覆盖】的子标题下面，层级就比较多了。

2024-01-23 07:26 UTC, oasis-cloud requested changes

2024-01-23 07:26 UTC, oasis-cloud commented on src/packages/configprovider/doc.md
> +##### Textarea 默认
configprovider 组件更偏向说明，不必和例子对应，此组件的重点不在右侧演示的例子上。可以调整下 demo 的顺序，因为文档先讲了 主题定制，然后才是国际化

2024-01-23 08:51 UTC, Alex-huxiyang commented on src/packages/configprovider/doc.md
> +##### Textarea 默认
明白，doc和demo重新调整了下

2024-01-25 02:46 UTC, oasis-cloud approved these changes

2024-01-25 02:46 UTC, merged