fix(image): 统一与调整demo&doc、统一代码风格
jdf2e/nutui-react pull request #1887
Opened 2024-01-22 09:27 UTC by Alex-huxiyang

### 🤔 这个变动的性质是？

- [ ] 新特性提交
- [ ] 日常 bug 修复
- [x] 站点、文档改进
- [x] 演示代码改进
- [ ] 组件样式/交互改进
- [ ] TypeScript 定义更新
- [ ] 包体积优化
- [ ] 性能优化
- [ ] 功能增强
- [ ] 国际化改进
- [ ] 重构
- [x] 代码风格优化
- [ ] 测试用例
- [ ] 分支合并
- [ ] 其他改动（是关于什么的改动？）

### 🔗 相关 Issue

### 💡 需求背景和解决方案

### ☑️ 请求合并前的自查清单

⚠️ 请自检并全部**勾选全部选项**。⚠️

- [x] 文档已补充或无须补充
- [x] 代码演示已提供或无须提供
- [x] TypeScript 定义已补充或无须补充
- [x] fork仓库代码是否为最新避免文件冲突
- [x] Files changed 没有 package.json lock 等无关文件

2024-01-23 07:20 UTC, oasis-cloud requested changes

2024-01-23 07:20 UTC, oasis-cloud commented on src/packages/image/doc.taro.md
> +    'https://storage.360buyimg.com/imgtools/e067cd5b69-07c864c0-dd02-11ed-8b2c-d7f58b17086a.png'
taro 文档中的 介绍可以改一下，改为：借助 Taro Image 标签实现，可以透传使用 Taro Image 的属性。

2024-01-23 07:20 UTC, oasis-cloud commented on src/packages/image/doc.taro.md
> +| lazy | 是否为懒加载图片 | `boolean` | `false` |
新增加的这些属性，需要再 taro 文档中确认是否存在，以及取值是什么

2024-01-23 07:20 UTC, oasis-cloud commented on src/packages/image/doc.taro.md
> +### ImagePosition 图片位置
新增加的这些属性，需要再 taro 文档中确认是否存在，以及取值是什么

2024-01-23 08:28 UTC, Alex-huxiyang commented on src/packages/image/doc.taro.md
> +### ImagePosition 图片位置
这些属性在taro不存在。已删除

2024-01-25 02:25 UTC, oasis-cloud approved these changes

2024-01-25 02:27 UTC, merged