feat(navbar): title区域自适应宽度
jdf2e/nutui-react pull request #1891
Opened 2024-01-23 06:24 UTC by irisSong

### 🤔 这个变动的性质是？

- [ ] 新特性提交
- [ ] 日常 bug 修复
- [ ] 站点、文档改进
- [ ] 演示代码改进
- [ ] 组件样式/交互改进
- [ ] TypeScript 定义更新
- [ ] 包体积优化
- [ ] 性能优化
- [ ] 功能增强
- [ ] 国际化改进
- [ ] 重构
- [ ] 代码风格优化
- [ ] 测试用例
- [ ] 分支合并
- [ ] 其他改动（是关于什么的改动？）

### 🔗 相关 Issue

### 💡 需求背景和解决方案

### ☑️ 请求合并前的自查清单

⚠️ 请自检并全部**勾选全部选项**。⚠️

- [ ] 文档已补充或无须补充
- [ ] 代码演示已提供或无须提供
- [ ] TypeScript 定义已补充或无须补充
- [ ] fork仓库代码是否为最新避免文件冲突
- [ ] Files changed 没有 package.json lock 等无关文件

2024-01-23 07:39 UTC, oasis-cloud requested changes

2024-01-23 07:39 UTC, oasis-cloud commented on src/packages/navbar/navbar.tsx
> +          maxWidth: contentRealWidth,
值都是同一个，为什么要分别设置 min、max，只设置 width 会有异常吗？

2024-01-23 07:39 UTC, oasis-cloud commented on src/packages/navbar/navbar.tsx
> +        (leftRectWidth > rightRectWidth
这里的算法是考虑到什么情况了？

2024-01-24 01:39 UTC, irisSong commented on src/packages/navbar/navbar.tsx
> +        (leftRectWidth > rightRectWidth
> 这里的算法是考虑到什么情况了？

left、right内容区域不同宽， title区域居中

2024-01-24 01:45 UTC, irisSong commented on src/packages/navbar/navbar.tsx
> +          maxWidth: contentRealWidth,
> 值都是同一个，为什么要分别设置 min、max，只设置 width 会有异常吗？

设置 min 是为了限制样式中兜底的min，设置 max 是为了flex布局，right区域是定位不占位问题

2024-01-24 02:09 UTC, irisSong commented on src/packages/navbar/navbar.tsx
> +          maxWidth: contentRealWidth,
> > 值都是同一个，为什么要分别设置 min、max，只设置 width 会有异常吗？
> 
> 设置 min 是为了限制样式中兜底的min，设置 max 是为了flex布局，right区域是定位不占位问题

title居左布局，title宽度改成样式实现，已提交

2024-01-24 06:07 UTC, xiaoyatong commented on src/packages/navbar/navbar.scss
> +    & > div {
如果是 rn 或者鸿蒙系统，可能无法匹配div

2024-01-25 01:22 UTC, irisSong commented on src/packages/navbar/navbar.scss
> +    & > div {
> 如果是 rn 或者鸿蒙系统，可能无法匹配div
改为demo中实现

2024-01-26 06:59 UTC, merged