feat(Popover): 增加light和dark模式的区分
jdf2e/nutui-react pull request #1977
Opened 2024-03-04 09:28 UTC by xiaoyatong

### 🤔 这个变动的性质是？

- [x] 新特性提交
- [ ] 日常 bug 修复
- [ ] 站点、文档改进
- [ ] 演示代码改进
- [ ] 组件样式/交互改进
- [ ] TypeScript 定义更新
- [ ] 包体积优化
- [ ] 性能优化
- [ ] 功能增强
- [ ] 国际化改进
- [ ] 重构
- [ ] 代码风格优化
- [ ] 测试用例
- [ ] 分支合并
- [ ] 其他改动（是关于什么的改动？）

### 🔗 相关 Issue

### 💡 需求背景和解决方案

### ☑️ 请求合并前的自查清单

⚠️ 请自检并全部**勾选全部选项**。⚠️

- [ ] 文档已补充或无须补充
- [ ] 代码演示已提供或无须提供
- [ ] TypeScript 定义已补充或无须补充
- [ ] fork仓库代码是否为最新避免文件冲突
- [ ] Files changed 没有 package.json lock 等无关文件

2024-03-04 09:40 UTC, oasis-cloud requested changes

2024-03-04 09:40 UTC, oasis-cloud commented on src/packages/popover/popover.tsx
> +  theme: 'light',
为什么不通过主题定制方式实现，而是提供 theme 属性？

2024-03-04 10:31 UTC, xiaoyatong commented on src/packages/popover/popover.tsx
> +  theme: 'light',
这种模式，就是我们没有识别到，在light模式下，会有 dark 的气泡场景。

2024-03-06 03:03 UTC, oasis-cloud requested changes

2024-03-06 03:03 UTC, oasis-cloud commented on src/packages/popover/index.ts
> +export type { PopoverProps } from './popover'
为什么要删除另外两个类型？组件类型的出口是 index 文件

2024-03-06 09:56 UTC, xiaoyatong commented on src/packages/popover/index.ts
> +export type { PopoverProps } from './popover'
fixed

2024-03-07 01:44 UTC, oasis-cloud approved these changes

2024-03-07 01:44 UTC, merged