fix(table): demo拆解与规范
jdf2e/nutui-react pull request #2074
Opened 2024-03-19 12:17 UTC by Alex-huxiyang

### 🤔 这个变动的性质是？

- [ ] 新特性提交
- [ ] 日常 bug 修复
- [x] 站点、文档改进
- [ ] 演示代码改进
- [ ] 组件样式/交互改进
- [ ] TypeScript 定义更新
- [ ] 包体积优化
- [ ] 性能优化
- [ ] 功能增强
- [ ] 国际化改进
- [ ] 重构
- [ ] 代码风格优化
- [ ] 测试用例
- [ ] 分支合并
- [ ] 其他改动（是关于什么的改动？）

### 🔗 相关 Issue

### 💡 需求背景和解决方案

### ☑️ 请求合并前的自查清单

⚠️ 请自检并全部**勾选全部选项**。⚠️

- [x] 文档已补充或无须补充
- [x] 代码演示已提供或无须提供
- [x] TypeScript 定义已补充或无须补充
- [x] fork仓库代码是否为最新避免文件冲突
- [x] Files changed 没有 package.json lock 等无关文件

2024-03-20 06:25 UTC, eiinu commented on src/packages/table/doc.en-US.md
> +### Whether to Show Borders, Text Alignment
英文文档中的 demo 标题，和 demo 代码中实际的英文版本不一致

2024-03-20 06:26 UTC, eiinu commented on src/packages/table/doc.en-US.md
> +## Code Demonstration
英文文档中这些标题和其他组件不一致

2024-03-20 08:14 UTC, oasis-cloud requested changes

2024-03-20 08:14 UTC, oasis-cloud commented on src/packages/table/doc.md
文档中的 table props 缺少了 sorterIcon， TableColumnProps 实际上并没有sorterIcon

2024-03-20 08:14 UTC, oasis-cloud commented on src/packages/table/doc.md
其他文档也需要查看一下是不是这个情况

2024-03-21 06:14 UTC, oasis-cloud approved these changes

2024-03-21 06:14 UTC, merged