feat(prrogress):: 适配lazy属性在Taro中不同端的错误
jdf2e/nutui-react pull request #2108
Opened 2024-03-22 01:22 UTC by Alex-huxiyang

### 🤔 这个变动的性质是？

- [x] 新特性提交
- [ ] 日常 bug 修复
- [x] 站点、文档改进
- [ ] 演示代码改进
- [ ] 组件样式/交互改进
- [ ] TypeScript 定义更新
- [ ] 包体积优化
- [ ] 性能优化
- [ ] 功能增强
- [ ] 国际化改进
- [ ] 重构
- [ ] 代码风格优化
- [ ] 测试用例
- [ ] 分支合并
- [ ] 其他改动（是关于什么的改动？）

### 🔗 相关 Issue

### 💡 需求背景和解决方案

### ☑️ 请求合并前的自查清单

⚠️ 请自检并全部**勾选全部选项**。⚠️

- [x] 文档已补充或无须补充
- [x] 代码演示已提供或无须提供
- [x] TypeScript 定义已补充或无须补充
- [x] fork仓库代码是否为最新避免文件冲突
- [x] Files changed 没有 package.json lock 等无关文件

2024-03-22 09:39 UTC, oasis-cloud requested changes

2024-03-22 09:39 UTC, oasis-cloud commented on src/packages/progress/progress.taro.tsx
> +        .observe('.nut-progress-lazy', (res: any) => {
这里加一下唯一的 class，建议使用 id 选择器，参考 tabs 组件 useUuid 方法

2024-03-22 09:39 UTC, oasis-cloud commented on src/packages/progress/progress.taro.tsx
> +        }, options)
options 是不是直接放这里，都是一次性的使用，而且还能减少看上去像是重复的代码

2024-03-22 09:39 UTC, oasis-cloud commented on src/packages/progress/progress.taro.tsx
```js
if (delay) {
      setDispalyPercent(0)
      timer = setTimeout(() => {
        setDispalyPercent(percent)
      }, delay)
    }

    return () => {
      observer && observer.disconnect()
      timer && clearTimeout(timer)
    }
```
```js
 if (delay) {
        setDispalyPercent(0)
        timer = setTimeout(() => {
          setDispalyPercent(percent)
        }, delay)
      }

      return () => {
        lazy && resetObserver()
        timer && clearTimeout(timer)
      }
```
这两块代码相似度太高了，差一点比较单一，可以考虑如何抽象一点

2024-03-22 10:58 UTC, xiaoyatong commented on src/packages/progress/progress.taro.tsx
> +  useEffect(() => {
这块代码可以分开封装。

2024-03-25 06:38 UTC, xiaoyatong commented on src/packages/progress/demos/taro/demo7.tsx
> +              Taro.showToast({ title: '进度已为100%' })
可改为 nutui 的组件。

2024-03-25 06:38 UTC, xiaoyatong commented on src/packages/progress/doc.zh-TW.md
>  ### 設置狀態顯示
替换下

2024-03-25 07:06 UTC, merged