fix(DatePicker): demo拆解与规范
jdf2e/nutui-react pull request #2133
Opened 2024-03-25 09:55 UTC by yeyu98

### 🤔 这个变动的性质是？

- [ ] 新特性提交
- [ ] 日常 bug 修复
- [ ] 站点、文档改进
- [x] 演示代码改进
- [ ] 组件样式/交互改进
- [ ] TypeScript 定义更新
- [ ] 包体积优化
- [ ] 性能优化
- [ ] 功能增强
- [ ] 国际化改进
- [ ] 重构
- [ ] 代码风格优化
- [ ] 测试用例
- [ ] 分支合并
- [ ] 其他改动（是关于什么的改动？）

### 🔗 相关 Issue

### 💡 需求背景和解决方案

### ☑️ 请求合并前的自查清单

⚠️ 请自检并全部**勾选全部选项**。⚠️

- [x] 文档已补充或无须补充
- [x] 代码演示已提供或无须提供
- [x] TypeScript 定义已补充或无须补充
- [x] fork仓库代码是否为最新避免文件冲突
- [x] Files changed 没有 package.json lock 等无关文件

2024-03-25 10:09 UTC, oasis-cloud requested changes

2024-03-25 10:09 UTC, oasis-cloud commented on src/packages/datepicker/demos/h5/demo1.tsx
> +interface PickerOption {
import { DatePicker, Cell, type DatePickerProps } from '@nutui/nutui-react'

需要修改 index.ts 和 index.taro.ts 将类型导出

2024-03-25 10:09 UTC, oasis-cloud commented on src/packages/datepicker/demos/h5/demo1.tsx
> +const Demo1 = () => {
可以调整 demo 代码的可读性，比如 confirm1 confirm10、show1 desc1 的命名。

2024-03-26 03:31 UTC, yeyu98 commented on src/packages/datepicker/demos/h5/demo1.tsx
> +const Demo1 = () => {
已调整

2024-03-26 03:31 UTC, yeyu98 commented on src/packages/datepicker/demos/h5/demo1.tsx
> +interface PickerOption {
已修改

2024-03-28 02:39 UTC, merged