fix(configprovider): demo 适配 rn & harmony, 调整 cell rtl 样式
jdf2e/nutui-react pull request #2347
Opened 2024-06-12 07:46 UTC by xiaoyatong

### 🤔 这个变动的性质是？

- [ ] 新特性提交
- [x] 日常 bug 修复
- [ ] 站点、文档改进
- [ ] 演示代码改进
- [ ] 组件样式/交互改进
- [ ] TypeScript 定义更新
- [ ] 包体积优化
- [ ] 性能优化
- [ ] 功能增强
- [ ] 国际化改进
- [ ] 重构
- [ ] 代码风格优化
- [ ] 测试用例
- [ ] 分支合并
- [ ] 其他改动（是关于什么的改动？）

### 🔗 相关 Issue

### 💡 需求背景和解决方案

### ☑️ 请求合并前的自查清单

⚠️ 请自检并全部**勾选全部选项**。⚠️

- [ ] 文档已补充或无须补充
- [ ] 代码演示已提供或无须提供
- [ ] TypeScript 定义已补充或无须补充
- [ ] fork仓库代码是否为最新避免文件冲突
- [ ] Files changed 没有 package.json lock 等无关文件

2024-06-13 03:40 UTC, oasis-cloud requested changes

2024-06-13 03:40 UTC, oasis-cloud commented on src/packages/configprovider/configprovider.taro.tsx
> +        className={classNames(classPrefix, className)}
为什么删除了 nut-${direciton} ？

2024-06-13 10:59 UTC, xiaoyatong commented
鸿蒙暂时不支持，暂无计划，待定。

2024-06-13 11:06 UTC, xiaoyatong commented on src/packages/configprovider/configprovider.taro.tsx
> +        className={classNames(classPrefix, className)}
统一升级新方式~

2024-06-17 13:28 UTC, oasis-cloud approved these changes

2024-06-17 13:30 UTC, merged