chore: run md-table-format when git commit changes
jdf2e/nutui-react pull request #2484
Opened 2024-07-25 09:25 UTC by Alex-huxiyang

增加table-format prettier插件，commit时自动以“紧凑规则”格式化改动的md。
本次文件改动大是手动执行了npx prettier --write "**/*.md" 的结果，每次commit只会对改动的md进行format
- [x] 重构

2024-07-25 12:02 UTC, oasis-cloud requested changes

2024-07-25 12:02 UTC, oasis-cloud commented on package.json
> +    "*.md": ["npx prettier --write"]
改成 "*.{scss,md}": "prettier --write",

2024-07-25 12:05 UTC, Alex-huxiyang commented on package.json
> +    "*.md": ["npx prettier --write"]
done

2024-07-26 01:42 UTC, oasis-cloud approved these changes

2024-07-26 01:42 UTC, merged