refactor(uploader): Upoader 3.0
jdf2e/nutui-react pull request #2660
Opened 2024-10-24 02:04 UTC by Alex-huxiyang

### 🤔 这个变动的性质是？

- [ ] 新特性提交
- [ ] 日常 bug 修复
- [ ] 站点、文档改进
- [ ] 演示代码改进
- [ ] 组件样式/交互改进
- [ ] TypeScript 定义更新
- [ ] 包体积优化
- [ ] 性能优化
- [ ] 功能增强
- [ ] 国际化改进
- [ ] 重构
- [ ] 代码风格优化
- [ ] 测试用例
- [ ] 分支合并
- [ ] 其他改动（是关于什么的改动？）

### 🔗 相关 Issue

### 💡 需求背景和解决方案

### ☑️ 请求合并前的自查清单

⚠️ 请自检并全部**勾选全部选项**。⚠️

- [ ] 文档已补充或无须补充
- [ ] 代码演示已提供或无须提供
- [ ] TypeScript 定义已补充或无须补充
- [ ] fork仓库代码是否为最新避免文件冲突
- [ ] Files changed 没有 package.json lock 等无关文件

2024-11-04 06:34 UTC, oasis-cloud commented
<img width="1187" alt="image" src="https://github.com/user-attachments/assets/7b203b25-6b5a-45d8-b788-5ac769ceec2c">
pnpm dev 的 H5

2024-11-04 07:01 UTC, oasis-cloud requested changes

2024-11-04 07:01 UTC, oasis-cloud commented on src/packages/uploader/file-item.ts
> +export type FileItemStatus = 'ready' | 'uploading' | 'success' | 'error'
fileItem 下相关的类型导出需要再 组件的 index 文件中处理。否则无法正确导出类型。

2024-11-04 07:01 UTC, oasis-cloud commented on src/packages/uploader/demos/h5/demo1.tsx
> +import { FileItem } from '../../file-item'
demo 中的类型需要从 @nutui 包中引入

2024-11-06 02:41 UTC, oasis-cloud commented on src/packages/uploader/uploader.tsx
> +      (children || previewType === 'list') && (
选择唯一的判断条件，避免歧义。

2024-11-06 02:42 UTC, oasis-cloud commented on src/packages/uploader/uploader.tsx
> +      Number(maxCount) > fileList.length &&
给这个条件判断提炼个变量，方便理解含义。

2024-11-06 02:48 UTC, oasis-cloud commented on src/packages/uploader/uploader.tsx
> +    _files = filterFiles(new Array<File>().slice.call(files))
反正都要转数组，可以在最开始做个变量出来

2024-11-06 03:08 UTC, oasis-cloud commented
AI 针对 uloader.tsx 和 uploader.taro.tsx 文件提出的建议中，重点关注抛错给用户的细节处理。可以把这部分补充下。

2024-11-06 03:10 UTC, oasis-cloud commented
需要增加 V2 升级 V3 的说明文档。

2024-11-06 04:47 UTC, oasis-cloud commented
<img width="243" alt="image" src="https://github.com/user-attachments/assets/fb2a4a02-bc34-4e2c-b026-8bf1cc861129">
鸿蒙下可点击区域太小。

2024-11-07 01:57 UTC, Alex-huxiyang commented
> <img alt="image" width="243" src="https://private-user-images.githubusercontent.com/12181600/383410673-fb2a4a02-bc34-4e2c-b026-8bf1cc861129.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA5NDM2MDYsIm5iZiI6MTczMDk0MzMwNiwicGF0aCI6Ii8xMjE4MTYwMC8zODM0MTA2NzMtZmIyYTRhMDItYmMzNC00ZTJjLWIwMjYtOGJmMWNjODYxMTI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA3VDAxMzUwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQzNTI5MmQ3MGVkMTMyNTIyMzg0MGQ4MmY4YTBlZDcxNjgxOGQ2YTRkMTFmMmVjMWI3ZWMxN2VkMWE2MjVkNzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.kr-Vs3wnsTtHsixr6jyJmMYFbrjm4SPfmtzIAeTnBmQ"> 鸿蒙下可点击区域太小。

这个是受到了button组件可点击区域的影响了，右侧部分点击失效。应该会一起修复

> <img alt="image" width="243" src="https://private-user-images.githubusercontent.com/12181600/383410673-fb2a4a02-bc34-4e2c-b026-8bf1cc861129.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA5NDM2MDYsIm5iZiI6MTczMDk0MzMwNiwicGF0aCI6Ii8xMjE4MTYwMC8zODM0MTA2NzMtZmIyYTRhMDItYmMzNC00ZTJjLWIwMjYtOGJmMWNjODYxMTI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA3VDAxMzUwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQzNTI5MmQ3MGVkMTMyNTIyMzg0MGQ4MmY4YTBlZDcxNjgxOGQ2YTRkMTFmMmVjMWI3ZWMxN2VkMWE2MjVkNzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.kr-Vs3wnsTtHsixr6jyJmMYFbrjm4SPfmtzIAeTnBmQ"> 鸿蒙下可点击区域太小。

2024-12-03 03:18 UTC, oasis-cloud approved these changes

2024-12-03 03:18 UTC, oasis-cloud commented on package.json
检查一下 packge.json 和 lock 文件与主分支的差异

2024-12-04 09:49 UTC, xiaoyatong commented on src/packages/uploader/demos/h5/demo1.tsx
> +  const uploaderStyle = {
可以使用 space

2024-12-04 09:49 UTC, xiaoyatong commented on src/packages/uploader/index.ts
> +type FileItem = {
独立放在util 文件中，同其他组件。

2024-12-06 08:01 UTC, oasis-cloud commented
单测提升下覆盖率

2024-12-24 03:12 UTC, merged