feat(hoverbutton): v14
jdf2e/nutui-react pull request #2810
Opened 2024-12-02 08:33 UTC by oasis-cloud

### 🤔 这个变动的性质是？

- [ ] 新特性提交
- [ ] 日常 bug 修复
- [ ] 站点、文档改进
- [ ] 演示代码改进
- [ ] 组件样式/交互改进
- [ ] TypeScript 定义更新
- [ ] 包体积优化
- [ ] 性能优化
- [ ] 功能增强
- [ ] 国际化改进
- [ ] 重构
- [ ] 代码风格优化
- [ ] 测试用例
- [ ] 分支合并
- [ ] 其他改动（是关于什么的改动？）

### 🔗 相关 Issue

### 💡 需求背景和解决方案

### ☑️ 请求合并前的自查清单

⚠️ 请自检并全部**勾选全部选项**。⚠️

- [ ] 文档已补充或无须补充
- [ ] 代码演示已提供或无须提供
- [ ] TypeScript 定义已补充或无须补充
- [ ] fork仓库代码是否为最新避免文件冲突
- [ ] Files changed 没有 package.json lock 等无关文件

2024-12-04 04:21 UTC, xiaoyatong reviewed
backtop 可以复用 hoverbutton~
可应用在 backtop中。

2024-12-04 04:21 UTC, xiaoyatong commented on src/packages/hoverbutton/hoverbutton.tsx
> +    const bottom = tabbarHeight + 60
可定义一个常量。

2024-12-04 04:21 UTC, xiaoyatong commented on src/packages/hoverbutton/demos/h5/demo6.tsx
> + */
icon+文字，建议作为一种通用规范实现，不是以demo的方式输出。

2024-12-04 04:21 UTC, xiaoyatong commented
<img width="54" alt="image" src="https://github.com/user-attachments/assets/d5e1f7a7-13b1-4ed7-85d7-25655dfb5453">
鸿蒙下字体没有生效。

2024-12-04 07:35 UTC, xiaoyatong commented on src/packages/hoverbuttonitem/hoverbuttonitem.taro.tsx
> +            size: 20,
size 值 是否需要写死

2024-12-04 07:35 UTC, xiaoyatong commented on src/packages/hoverbuttonitem/hoverbuttonitem.taro.tsx
> +            size: 14,
同上

2024-12-04 07:35 UTC, xiaoyatong commented on src/packages/hoverbuttonitem/hoverbuttonitem.taro.tsx
> +            size: 20,
可移入样式中

2024-12-04 08:57 UTC, irisSong requested changes
单测和coverage改一下

2024-12-05 03:47 UTC, irisSong approved these changes

2024-12-05 07:28 UTC, merged