feat: Address 组件开发
jdf2e/nutui-react pull request #44
Opened 2021-12-03 03:24 UTC by yangxiaolu1993

feat: Address 组件开发

2021-12-03 03:24 UTC, yangxiaolu1993 commented
feat: Address 组件开发

2021-12-08 06:43 UTC, oasis-lab requested changes

2021-12-08 06:43 UTC, oasis-lab commented on src/packages/address/address.scss
> +    color: #333;
色值可以使用 variable.scss 中的变量吗

2021-12-08 06:43 UTC, oasis-lab commented on src/packages/address/address.tsx
> +  selected?: (prevExistAdd: any, item: any, copyExistAdd: any) => void
事件名称改成 onSelected

2021-12-08 06:43 UTC, oasis-lab commented on src/packages/address/address.tsx
> +  close?: (cal: any) => void
事件名称改成 onClose，cal 是不是可以按照文档把类型定义更明确一些，以便代码提示

2021-12-08 06:43 UTC, oasis-lab commented on src/packages/address/address.tsx
> +export interface AddressProps {
注意组件是否支持 className 和 style 等

2021-12-08 06:43 UTC, oasis-lab commented on src/packages/address/address.tsx
> +    // emit('update:visible', false);
清理类似的注释

2021-12-08 06:47 UTC, oasis-lab requested changes

2021-12-08 06:47 UTC, oasis-lab commented on src/packages/address/doc.md
> +| exist-address | 已存在地址列表，每个地址对象中，必传值provinceName、cityName、countyName、townName、addressDetail、selectedAddress（字段解释见下） | Array | []
属性采用驼峰写法，其他非驼峰的需要修改

2021-12-08 06:47 UTC, oasis-lab commented on src/packages/address/doc.md
> +| close | 地址选择弹框关闭时触发 | 参考 close
事件名称统一成 onXxxx

2021-12-20 09:28 UTC, merged