Skeleton 骨架屏代码提交
jdf2e/nutui-react pull request #96
Opened 2022-02-18 11:41 UTC by junjun666

已自测
文档已开发

2022-03-04 08:21 UTC, oasis-cloud requested changes

2022-03-04 08:21 UTC, oasis-cloud commented on src/packages/skeleton/doc.md
> +```
这里需要加 ::: 来结束 demo 块，每个 demo 块都是如此，目前 React 库采用的包和 Vue 的有区别，Vue 的对未结束的识别不出来

2022-03-04 08:21 UTC, oasis-cloud commented on src/packages/skeleton/skeleton.tsx
> +                {title && <div className="title"></div>}
className="title" 存在全局样式污染的可能，遵守 BEM 规范

2022-03-04 09:32 UTC, irisSong commented on src/packages/skeleton/skeleton.tsx
> +    return items
66-70，可修改为 
return Array.from({ length: num-1 }, (v, i) => i)

2022-03-07 08:33 UTC, junjun666 commented on src/packages/skeleton/doc.md
> +```
已修复~

2022-03-07 08:44 UTC, junjun666 commented on src/packages/skeleton/doc.md
> +```
其他组件已检查修复~

2022-03-07 08:51 UTC, junjun666 commented on src/packages/skeleton/skeleton.tsx
> +    return items
Got it~已采纳

2022-03-07 09:45 UTC, junjun666 commented on src/packages/skeleton/skeleton.tsx
> +                {title && <div className="title"></div>}
已修改

2022-03-07 10:02 UTC, oasis-cloud approved these changes

2022-03-07 10:03 UTC, merged